add response for GH action slash command
defenseunicorns/delivery-aws-iac pull request #142
Opened 2023-04-06 14:26 UTC by zack-is-cool

addresses #135

2023-04-06 14:28 UTC, zack-is-cool commented
/test ping

2023-04-06 14:35 UTC, zack-is-cool commented
/test ping

2023-04-06 14:46 UTC, zack-is-cool commented
/test ping

2023-04-06 15:14 UTC, zack-is-cool commented
/test ping

2023-04-06 15:21 UTC, zack-is-cool commented
/test ping

2023-04-06 17:34 UTC, zack-is-cool commented
Ideally, we would have some kind of org-level bot account do this instead of having a specific user's pat.

2023-04-23 14:55 UTC, ntwkninja commented
@RothAndrew any thoughts here?

2023-04-27 21:08 UTC, RothAndrew requested changes

2023-04-27 21:08 UTC, RothAndrew commented on .github/workflows/test-command.yml
> +      - name: Create comment
```suggestion
      - name: Update comment
```

2023-04-27 21:08 UTC, RothAndrew commented on .github/workflows/test-command.yml
> +      #Will edit the comment that triggered the /test comment and add the run-url
```suggestion
      #Will update the comment that triggered the /test comment and add the run-url
```

2023-04-27 21:08 UTC, RothAndrew commented on .github/workflows/test-command.yml
> +      #Will edit the comment that triggered the /test comment and add the run-url
```suggestion
      #Will update the comment that triggered the /test comment and add the run-url
```

2023-04-27 21:08 UTC, RothAndrew commented on .github/workflows/test-command.yml
> +      - name: Create comment
```suggestion
      - name: Update comment
```

2023-04-27 22:03 UTC, RothAndrew approved these changes

2023-04-27 22:04 UTC, merged