Vpc secondary cidr
defenseunicorns/delivery-aws-iac pull request #173
Opened 2023-04-15 05:24 UTC by ntwkninja

2023-04-15 05:28 UTC, ntwkninja commented
/test all

2023-04-15 05:34 UTC, ntwkninja commented
/test all

2023-04-15 06:23 UTC, ntwkninja commented
/test all

2023-04-15 06:29 UTC, ntwkninja commented
/test all

2023-04-17 15:49 UTC, ntwkninja commented
/test all

2023-04-17 16:36 UTC, ntwkninja commented
expecting this will be a discussion

2023-04-17 17:07 UTC, RothAndrew requested changes, later dismissed
Would you mind updating the PR description with a high level description of what is being done here? I'm seeing:

* Add ability to define secondary CIDR blocks in the VPC
* Remove support for EKS v1.23
* Add support for EKS v1.26

The title says "operationalize Calico" as well, can you clarify what that means?

2023-04-17 17:07 UTC, RothAndrew commented on examples/complete/variables.tf
> +    condition     = contains(["1.26"], var.cluster_version)
Just making sure it is super clear and understood. We want to actually remove support for 1.23, and only support 1.26 from this point on (until such point that we decide to add more)?

2023-04-17 17:08 UTC, RothAndrew commented
Is this PR closing any issues? If so, please add "Closes #XXX" to the description

2023-04-17 17:11 UTC, RothAndrew commented
We don't currently test in GovCloud. Have we confirmed that EKS v1.26 and the brand new AMI that fixed the containerd issue are available in GovCloud?

2023-04-17 17:16 UTC, brianrexrode commented
Please see my comment here https://github.com/defenseunicorns/iac/issues/53#issuecomment-1509352633

2023-04-17 18:20 UTC, RothAndrew commented on README.md
> +- Zarf > v0.25.x
```suggestion
- EKS >= v1.26.x
- Big Bang >= v2.x.x
- Zarf >= v0.25.x
```

2023-04-17 20:23 UTC, ntwkninja commented on examples/complete/fixtures.secure.tfvars
> +secondary_cidr_blocks          = ["100.64.0.0/16"] #https://aws.amazon.com/blogs/containers/optimize-ip-addresses-usage-by-pods-in-your-amazon-eks-cluster/
will remove

2023-04-17 20:37 UTC, ntwkninja commented on examples/complete/variables.tf
> +    condition     = contains(["1.26"], var.cluster_version)
Agree, the plan is to add a breaking change note in the release notes indicating that there isn't an upgrade path and we're currently only supporting 1.26.

2023-04-18 11:25 UTC, ntwkninja commented on examples/complete/fixtures.common.tfvars
> +enable_aws_node_termination_handler      = false
INFO: https://github.com/aws/aws-node-termination-handler

As Rex mentioned in a different issue, our current default cannot deploy on k8s >=1.25 because PSPs were deprecated. We receive the following error.

│ Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "aws-node-termination-handler" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
│ ensure CRDs are installed first
│ 
│   with module.eks.module.eks_blueprints_kubernetes_addons.module.aws_node_termination_handler[0].module.helm_addon.helm_release.addon[0],
│   on .terraform/modules/eks.eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {

2023-04-19 02:05 UTC, ntwkninja commented
progress
![image](https://user-images.githubusercontent.com/70963120/232947676-9ce29315-a54c-4ee9-83c0-da4089e2282a.png)

2023-04-19 03:49 UTC, ntwkninja commented on examples/complete/fixtures.common.tfvars
> +enable_aws_node_termination_handler      = false
opened #180

2023-04-19 04:01 UTC, ntwkninja commented
> We don't currently test in GovCloud. Have we confirmed that EKS v1.26 and the brand new AMI that fixed the containerd issue are available in GovCloud?

yes

2023-04-19 04:03 UTC, ntwkninja commented
/test all

2023-04-19 12:20 UTC, ntwkninja commented
/test all

2023-04-19 21:39 UTC, ntwkninja commented
/test all

2023-04-22 00:44 UTC, ntwkninja commented
/test all

2023-04-23 14:55 UTC, ntwkninja commented
/test all

2023-04-23 19:35 UTC, brianrexrode submitted a review, later dismissed
🤷 🤞 🍀

2023-04-23 19:45 UTC, brianrexrode approved these changes
fixed pre-commit 👍

2023-04-23 20:13 UTC, merged