fix delivery-aws-iac repo references
defenseunicorns/delivery-aws-iac pull request #196
Opened 2023-04-24 13:55 UTC by brianrexrode

replace all references to defenseunicorns/iac to defenseunicorns/delivery-aws-iac

2023-04-24 16:04 UTC, RothAndrew commented on CODEOWNERS
> +* @defenseunicorns/delivery-aws-iac
We'll need to rename the GitHub Team that is currently named `iac`. Do we just want to do that for now? I do think it may be worth looking at that Team (and the `iac-admin` team) and making sure the right people are in it.

2023-04-24 16:04 UTC, RothAndrew commented
/test all

2023-04-24 16:34 UTC, brianrexrode commented on CODEOWNERS
> +* @defenseunicorns/delivery-aws-iac
We can rename it for now and review the members now or later. I'm good either way

2023-04-27 21:03 UTC, RothAndrew requested changes

2023-04-27 21:03 UTC, RothAndrew commented on CODEOWNERS
>  /CODEOWNERS @defenseunicorns/iac-admin
Change these to `@defenseunicorns/delivery-aws-iac-admin`

2023-04-27 22:19 UTC, RothAndrew commented on CODEOWNERS
>  /CODEOWNERS @defenseunicorns/iac-admin
Ah yep you're right sorry

2023-04-27 22:19 UTC, RothAndrew approved these changes

2023-04-27 22:22 UTC, merged