fix s3 bucket empty output intermittent errors
defenseunicorns/delivery-aws-iac pull request #215
Opened 2023-05-02 16:19 UTC by zack-is-cool

fixes #207

2023-05-02 17:11 UTC, zack-is-cool commented
/test all

2023-05-02 17:11 UTC, zack-is-cool commented
/test all

2023-05-02 17:11 UTC, zack-is-cool commented
/test all

2023-05-02 21:00 UTC, zack-is-cool commented
/test all

2023-05-02 21:00 UTC, zack-is-cool commented
/test all

2023-05-02 21:00 UTC, zack-is-cool commented
/test all

2023-05-02 21:20 UTC, zack-is-cool commented
/test all

2023-05-02 21:20 UTC, zack-is-cool commented
/test all

2023-05-02 21:20 UTC, zack-is-cool commented
/test all

2023-05-02 21:20 UTC, zack-is-cool commented
/test all

2023-05-02 21:21 UTC, zack-is-cool commented
/test all

2023-05-02 21:54 UTC, zack-is-cool commented
/test all

2023-05-02 21:54 UTC, zack-is-cool commented
/test all

2023-05-02 21:54 UTC, zack-is-cool commented
/test all

2023-05-02 21:54 UTC, zack-is-cool commented
/test all

2023-05-02 22:14 UTC, zack-is-cool commented
/test all

2023-05-02 22:14 UTC, zack-is-cool commented
/test all

2023-05-02 22:14 UTC, zack-is-cool commented
/test all

2023-05-02 22:14 UTC, zack-is-cool commented
/test all

2023-05-02 23:25 UTC, zack-is-cool commented
/test all

2023-05-02 23:25 UTC, zack-is-cool commented
/test all

2023-05-02 23:26 UTC, zack-is-cool commented
/test all

2023-05-02 23:57 UTC, zack-is-cool commented
/test all

2023-05-02 23:57 UTC, zack-is-cool commented
/test all

2023-05-03 00:01 UTC, zack-is-cool commented
/test all

2023-05-03 00:05 UTC, zack-is-cool commented
/test all

2023-05-03 00:05 UTC, zack-is-cool commented
/test all

2023-05-03 14:23 UTC, zack-is-cool commented
/test all

2023-05-03 14:24 UTC, zack-is-cool commented
/test all

2023-05-03 14:42 UTC, zack-is-cool commented
/test all

2023-05-03 14:42 UTC, zack-is-cool commented
/test all

2023-05-03 19:43 UTC, zack-is-cool commented
/test all

2023-05-03 19:43 UTC, zack-is-cool commented
/test all

2023-05-03 20:33 UTC, zack-is-cool commented
/test all

2023-05-03 20:34 UTC, zack-is-cool commented
/test all

2023-05-03 20:49 UTC, zack-is-cool commented
/test all

2023-05-03 20:49 UTC, zack-is-cool commented
/test all

2023-05-03 20:49 UTC, zack-is-cool commented
/test all

2023-05-03 21:14 UTC, zack-is-cool commented
/test all

2023-05-03 21:14 UTC, zack-is-cool commented
/test all

2023-05-04 14:19 UTC, zack-is-cool commented
/test all

2023-05-04 14:19 UTC, zack-is-cool commented
/test all

2023-05-04 14:19 UTC, zack-is-cool commented
/test all

2023-05-04 14:56 UTC, zack-is-cool commented
/test all

2023-05-04 14:56 UTC, zack-is-cool commented
/test all

2023-05-04 14:56 UTC, zack-is-cool commented
/test all

2023-05-04 19:40 UTC, zack-is-cool commented
/test all

2023-05-04 19:53 UTC, zack-is-cool commented
/test all

2023-05-04 21:47 UTC, zack-is-cool commented
/test all

2023-05-04 21:48 UTC, zack-is-cool commented
/test all

2023-05-04 21:48 UTC, zack-is-cool commented
/test all

2023-05-05 15:11 UTC, zack-is-cool commented
/test all

2023-05-05 15:11 UTC, zack-is-cool commented
/test all

2023-05-05 15:25 UTC, zack-is-cool commented
/test all

2023-05-05 15:25 UTC, zack-is-cool commented
/test all

2023-05-05 15:25 UTC, zack-is-cool commented
/test all

2023-05-05 16:07 UTC, zack-is-cool commented
/test all

2023-05-05 16:07 UTC, zack-is-cool commented
/test all

2023-05-05 16:07 UTC, zack-is-cool commented
/test all

2023-05-05 16:07 UTC, zack-is-cool commented
/test all

2023-05-05 17:44 UTC, zack-is-cool commented
/test all

2023-05-05 17:44 UTC, zack-is-cool commented
/test all

2023-05-05 17:53 UTC, zack-is-cool commented
/test all

2023-05-05 17:53 UTC, zack-is-cool commented
/test all

2023-05-05 17:53 UTC, zack-is-cool commented
/test all

2023-05-05 18:00 UTC, zack-is-cool commented
/test all

2023-05-05 18:00 UTC, zack-is-cool commented
/test all

2023-05-05 18:00 UTC, zack-is-cool commented
/test all

2023-05-05 18:00 UTC, zack-is-cool commented
/test all

2023-05-05 18:00 UTC, zack-is-cool commented
/test all

2023-05-05 18:33 UTC, zack-is-cool commented
/test all
full test e2e

2023-05-08 20:06 UTC, RothAndrew requested changes

2023-05-08 20:06 UTC, RothAndrew commented on examples/complete/providers.tf
> +      version = "0.9.1"
Any particular reason for pinning the version?
```suggestion
      version = ">= 0.9.1"
```

2023-05-08 20:06 UTC, RothAndrew commented on modules/bastion/s3-buckets.tf
> +  target_bucket = var.access_logs_bucket_name
```suggestion
  target_bucket = data.aws_s3_bucket.access_logs_bucket.id
```

alternatively, we could evaluate whether that data object is still necessary. But as long as it exists, we should reference it rather than the var.

2023-05-09 14:26 UTC, zack-is-cool commented
> holy mother of slash commands batman

very intermittent error 😢

2023-05-09 17:19 UTC, RothAndrew commented
Is this ready for review and merge? I'm still seeing commits being pushed to it

2023-05-09 17:20 UTC, RothAndrew approved these changes

2023-05-09 18:03 UTC, merged