adding fix to example node groups
defenseunicorns/delivery-aws-iac pull request #279
Opened 2023-06-07 15:02 UTC by JaseKoonce

This PR replaces the `key_name =`statement in the example, previously you would get an error if `var.keycloak_enabled=false` because the key value would be empty.

2023-06-12 23:39 UTC, RothAndrew commented
This is a good quick fix of the underlying problem. It is also a good identifier of a gap in our testing suite. Thoughts on how to fix that gap?

@JaseKoonce are you blocked from making progress anywhere as long as this PR is unmerged?

If not blocked, I think it may be valuable to expand this PR to address the testing gap as well. If blocked, let's merge this and open an issue to address the gap.

I'm not wild about running a third test run in parallel, but that would do the trick, if we made the 3rd test run set `keycloak_enabled` to false. I think it's definitely worth putting our heads together for a couple minutes to see if there's a better way.

CC @ntwkninja

2023-06-12 23:40 UTC, RothAndrew commented
This is gonna be blocked from merging until https://github.com/defenseunicorns/delivery-aws-iac/pull/281 gets merged, as the testing pipeline will currently fail due to an unrelated issue with RDS.

2023-06-13 02:41 UTC, ntwkninja approved these changes
🚀

2023-06-13 02:44 UTC, ntwkninja requested changes
Missed @RothAndrew feedback on the RDS piece

2023-06-13 11:09 UTC, JaseKoonce commented
> @JaseKoonce are you blocked from making progress anywhere as long as this PR is unmerged?
> 


@RothAndrew It doesn't block my progress at all, so no rush from my side.

2023-06-13 16:30 UTC, RothAndrew commented
@JaseKoonce are you up for taking a crack at designing+implementing a fix for this gap in the test pipeline? I'm happy to help out however needed.

It'll be really good to get more people comfortable working with that stuff. I know I've been the one that has done most of it, would very much like to not end up being a bottleneck.

2023-06-13 16:45 UTC, JaseKoonce commented
@RothAndrew Definitely! It would be my first time adjusting the test pipeline, but Im happy to start taking a look at it and see what I can do. It may take a bit as I have some other things to take care of, but hopefully I can get started on it soon.

2023-06-13 16:53 UTC, RothAndrew commented
> @RothAndrew Definitely! It would be my first time adjusting the test pipeline, but Im happy to start taking a look at it and see what I can do. It may take a bit as I have some other things to take care of, but hopefully I can get started on it soon.

Sounds great. Please let me know if there anything I can do to help out.

2023-06-14 15:43 UTC, JaseKoonce commented
@RothAndrew @ntwkninja I just added in another test for variable validation. Currently it is just running a plan. From what I am seeing that should catch most of these types of errors without needing another E2E test. I currently have it as its own test, but it could easily be modified to be added to the end of another test if that makes more sense to you guys.

2023-06-14 15:49 UTC, RothAndrew commented
> @RothAndrew @ntwkninja I just added in another test for variable validation. Currently it is just running a plan. From what I am seeing that should catch most of these types of errors without needing another E2E test. I currently have it as its own test, but it could easily be modified to be added to the end of another test if that makes more sense to you guys.

Gotcha. I think that is fine. I wasn't tracking that this error would surface in a plan vs an apply. Agree that it will be a lot more efficient to just do a plan.

Will go through and review the code in a bit. Nice work.

2023-06-14 16:00 UTC, RothAndrew requested changes
Looks pretty good. Couple other fixes:

* Can we change the filename/function name? I feel like there is something more descriptive that could be used than "Variable". It should contain the word "Complete" as well since it is using the "examples/complete" folder. Maybe "TestExamplesCompletePlanOnly"? That way we could put other things in here later that would be able to be tested using just `terraform plan`.
* We also need a Makefile target added. If we use the recommendation from the previous bullet the target should be `make test-complete-plan-only`

2023-06-14 16:16 UTC, JaseKoonce commented
@RothAndrew Working on those final changes now, should have them ready for review in a few minutes.

2023-06-14 16:46 UTC, RothAndrew requested changes

2023-06-14 16:46 UTC, RothAndrew commented on Makefile
> +test-complete-plan-only: ## Run one test (TestExamplesCompletePlanOnly). Requires access to an AWS account. Costs real money.
```suggestion
test-complete-plan-only: ## Run one test (TestExamplesCompletePlanOnly). Does not require access to an AWS account since it is just running `terraform plan`.
```

2023-06-14 16:47 UTC, RothAndrew commented
That should be the last change. Everything else looks good. After your next commit push write `/test all` in a comment by itself to kick off the test pipeline

2023-06-14 16:50 UTC, JaseKoonce commented on Makefile
> +test-complete-plan-only: ## Run one test (TestExamplesCompletePlanOnly). Requires access to an AWS account. Costs real money.
It should still will require access to an account for the plan. Thanks for the catch on the money part, totally missed that.

2023-06-14 16:51 UTC, RothAndrew commented on Makefile
> +test-complete-plan-only: ## Run one test (TestExamplesCompletePlanOnly). Requires access to an AWS account. Costs real money.
ahh gotcha, that makes sense

2023-06-14 16:53 UTC, JaseKoonce commented on Makefile
> +test-complete-plan-only: ## Run one test (TestExamplesCompletePlanOnly). Requires access to an AWS account. Costs real money.
@RothAndrew Does the change in suggestion work for you?

2023-06-14 16:54 UTC, RothAndrew commented on Makefile
> +test-complete-plan-only: ## Run one test (TestExamplesCompletePlanOnly). Requires access to an AWS account. Costs real money.
yep

2023-06-14 16:57 UTC, JaseKoonce commented
/test all

2023-06-14 17:15 UTC, zack-is-cool commented
I think this TF might lead to an empty tuple error? Safest is it wrap it in a try() imo

2023-06-14 18:22 UTC, JaseKoonce commented
Looks like it failed based on a lack of IP's, shouldn't be a problem anymore.

2023-06-14 18:24 UTC, JaseKoonce commented
/test all

2023-06-14 18:25 UTC, RothAndrew commented
> Looks like it failed based on a lack of IP's, shouldn't be a problem anymore.

I'll go in and submit a request to increase the number of EIPs.

The new test passed. I'm comfortable with merging this without waiting for the full E2E if you are.

2023-06-14 18:32 UTC, ntwkninja approved these changes

2023-06-14 18:33 UTC, JaseKoonce commented
> > Looks like it failed based on a lack of IP's, shouldn't be a problem anymore.
> 
> I'll go in and submit a request to increase the number of EIPs.
> 
> The new test passed. I'm comfortable with merging this without waiting for the full E2E if you are.

@RothAndrew I'm okay with that, but I did already start the test. Is there any way to stop it without having to manually clean up resources?

2023-06-14 18:38 UTC, RothAndrew commented
No. Just leave it, it will clean up on its own. Merging the PR won't cancel the test run, it'll just finish on its own

2023-06-14 19:44 UTC, merged