Eks 1.27
defenseunicorns/delivery-aws-iac pull request #325
Opened 2023-08-01 20:24 UTC by ntwkninja

This PR upgrades EKS, adds gp3 default storage class option / exposes reclaim policy, removes components that are provisioned via dubbd-aws and upgrades eks add-ons.

2023-08-01 20:28 UTC, ntwkninja commented
/test all

2023-08-01 22:05 UTC, RothAndrew requested changes

2023-08-01 22:05 UTC, RothAndrew commented on examples/complete/fixtures.common.tfvars
> +  # ]
```suggestion

```

Unless we need to hang on to this commented out code for some reason let's delete it. If we do need it let's add a line comment saying why we need it.

2023-08-01 22:05 UTC, RothAndrew commented on examples/complete/k8s-secrets.tf
> -resource "kubernetes_secret_v1" "rds_postgres_keycloak_creds" {
I understand the reasoning behind deleting this secret, since it is for the RDS stuff that is getting deleted.

Can we add a different secret here so we don't lose the intent of providing a pattern as to how to create a secret?

2023-08-01 22:05 UTC, RothAndrew commented on examples/complete/variables.tf
> +    condition     = contains(["1.26", "1.27"], var.cluster_version)
Should we delete the 1.26 entry here? Since we are updating the tests to only test 1.27 the argument can be made that we no longer support 1.26

2023-08-02 13:59 UTC, ntwkninja commented on examples/complete/k8s-secrets.tf
> -resource "kubernetes_secret_v1" "rds_postgres_keycloak_creds" {
I captured the contents being removed in #328 to keep this PR from getting larger than it already is.

2023-08-02 14:14 UTC, ntwkninja commented
/test all

2023-08-02 15:06 UTC, RothAndrew commented on examples/complete/variables.tf
> +    condition     = contains(["1.26", "1.27"], var.cluster_version)
Works for me. Recommend adding that message to the `error_message` content

2023-08-02 15:36 UTC, ntwkninja commented
/test all

2023-08-02 15:37 UTC, RothAndrew commented on examples/complete/variables.tf
> +    condition     = contains(["1.26", "1.27"], var.cluster_version)
Ah yeah you're right, I wasn't thinking of it that way.

I'm okay with leaving it the way it is, as long as we add something somewhere that talks about what you were saying above. A line in the README.md would satisfy that too.

2023-08-02 15:43 UTC, RothAndrew approved these changes

2023-08-02 16:05 UTC, RothAndrew approved these changes

2023-08-03 02:07 UTC, ntwkninja commented
/test all

2023-08-03 05:24 UTC, merged