reduces e2e tests to 2 and allows running individually
defenseunicorns/delivery-aws-iac pull request #333
Opened 2023-08-10 04:14 UTC by zack-is-cool

closes #318
closes #319 

These changes modify the functionality of the test command

`/test e2e_secure` - just run secure test on govcloud
`/test e2e_insecure` - just run insecure test on commercial
`/test all` - run `e2e_secure` and `e2e_insecure` tests

2023-08-10 04:42 UTC, ntwkninja requested changes
minor change requested, otherwise lg2m

2023-08-10 04:42 UTC, ntwkninja commented on .github/actions/e2e/action.yml
> +        TF_VAR_region2: ${{ inputs.region2 }}
region2 var was refactored out when we removed the RDS module

2023-08-12 12:05 UTC, ntwkninja submitted a review, later dismissed
🚀

2023-08-12 12:06 UTC, ntwkninja commented
/test all

2023-08-12 18:33 UTC, zack-is-cool commented
@ntwkninja 
With the `peter-evans/slash-command-dispatch@v3` action we're using `repository` dispatch which only allows workflows on the repo's default branch (main) - see https://github.com/peter-evans/slash-command-dispatch/tree/v3/#dispatch-type. Basically this can't be tested _here_ until it's merged. 

Also I realized the other day that @RothAndrew already did some of this work (oops) so would probably like his input when he gets back.
https://github.com/defenseunicorns/delivery-aws-iac/pull/327

2023-08-15 19:50 UTC, RothAndrew commented on .github/actions/e2e/action.yml
> +      if: inputs.github-context == 'test / e2e-govcloud'
Instead of doing this let's add a new input variable called "test type" or something, with 2 valid strings of "secure" or "insecure" accepted, which would get used to pick which make target to run.

2023-08-15 20:23 UTC, zack-is-cool commented
@RothAndrew Changes LGTM

2023-08-15 20:24 UTC, RothAndrew approved these changes

2023-08-15 20:29 UTC, RothAndrew commented
Since we are changing the parse job the tests won't run properly until this is in main. Overriding the branch protections for this one and merging. Will follow up with any fixes as needed

2023-08-15 20:30 UTC, merged