docs: spike/adr for e2e testing
defenseunicorns/delivery-aws-iac pull request #354
Opened 2023-09-14 16:49 UTC by zack-is-cool

2023-09-14 17:45 UTC, ntwkninja requested changes

2023-09-14 17:45 UTC, ntwkninja commented on doc/adr/0010-e2e-testing-improvement.md
> +1. **Skip Unnecessary Runs**: Running e2e tests for changes that don't affect the code (e.g., updating READMEs) is inefficient.
I really like this

2023-09-14 17:45 UTC, ntwkninja commented on doc/adr/0010-e2e-testing-improvement.md
> +The secure test takes significantly longer to complete compared to the insecure test, doubling the time required for e2e tests to complete.
decision:
- In a PR we are able to run both insecure and secure tests 
  - not required to pass to be added to merge queue 
  - maintainers can use slash command dispatch
- Insecure test is required in merge event (merge queue... required) 
  - test must pass to merge to main
- Secure test is required to run at least nightly and be integrated with slack notification
  - maintains validation of all things
  - failures must become the top priority of the iac team
- Release Please PR should not be added to the merge queue unless the merge queue is empty
- This decision will be captured in the original testing ADR

2023-09-14 17:45 UTC, ntwkninja commented on doc/adr/0010-e2e-testing-improvement.md
> +The secure test takes significantly longer to complete compared to the insecure test, doubling the time required for e2e tests to complete.
- If it's a Release Please PR, it should run the secure test to ensure that all tests pass before a tag is cut
  - needed because Release Please kicks off a tag job when merged to main occurs

2023-09-15 15:12 UTC, zack-is-cool commented
/test all
I guess

2023-09-15 16:00 UTC, RothAndrew requested changes
ADR number 10 and number 11 read very similarly. Recommend scoping down to just one. The ADR that needs to be superceded is number 7.

2023-09-15 20:40 UTC, RothAndrew approved these changes

2023-09-16 00:30 UTC, ntwkninja approved these changes

2023-09-16 00:39 UTC, ntwkninja commented
/test all

2023-09-16 02:51 UTC, merged