Refactor away from aws blueprints + add custom vpc_cni AND add calico_cni
defenseunicorns/delivery-aws-iac pull request #96
Opened 2023-03-14 03:03 UTC by zack-is-cool

Very draft, much junk WIP

2023-03-14 16:07 UTC, RothAndrew commented
Looks like you are doing updates to the `complete-managed-nodegroup` and `complete-self-managed-nodegroup` examples, and adding a new example `complete-self-managed-ng-intra-subnets`.

My next step after merging #90 was to delete those two existing examples (first `complete-managed-nodegroup`, then `complete-self-managed-nodegroup` after the test for "secure mode" is done)

Adding another example on top concerns me, as it looks to be a lot of copy/pasted code again, which is going to negatively affect maintainability.

Understand that this is very much a WIP PR, but want to make sure we aren't moving in opposite directions.

2023-03-14 16:15 UTC, zack-is-cool commented
Yeah I wasn't intending for that folder to make it into main. Just extra scratch space as I worked through some of the new variables and logic while still looking at the old examples

2023-03-17 21:19 UTC, zack-is-cool commented
/test all

2023-03-17 21:26 UTC, zack-is-cool commented
/test all

2023-03-17 21:52 UTC, zack-is-cool commented
/test all

2023-03-17 22:10 UTC, zack-is-cool commented
/test all

2023-03-17 22:19 UTC, zack-is-cool commented
/test all

2023-03-17 22:46 UTC, zack-is-cool commented
/test all

2023-03-17 23:04 UTC, zack-is-cool commented
/test all

2023-03-17 23:29 UTC, zack-is-cool commented
/test all

2023-03-18 00:24 UTC, zack-is-cool commented
/test all

2023-03-18 04:44 UTC, zack-is-cool commented
/test all

2023-03-18 04:49 UTC, zack-is-cool commented
/test all

2023-03-21 04:10 UTC, zack-is-cool commented
/test all

2023-03-21 04:52 UTC, zack-is-cool commented
/test all

2023-03-21 16:21 UTC, RothAndrew commented
Can you please add "Closes #XXX" for any issues this is intending to close to the description?

2023-03-21 22:39 UTC, RothAndrew requested changes

2023-03-21 22:39 UTC, RothAndrew commented on examples/complete-self-managed-nodegroup/variables.tf
> +variable "loki_s3_bucket_kms_key_alias" {
This is a dead variable. It's value is never read

2023-03-21 22:39 UTC, RothAndrew commented on examples/complete/main.tf
> +data "aws_ami" "eks_default" {
This data resource looks identical to `data.aws_ami.amazonlinux2eks` other than one uses `-v*` and the other uses `-*`. Recommend deleting one of them.

2023-03-21 22:39 UTC, RothAndrew commented on examples/complete/main.tf
> +  version = "~> 2.0"
Pin to a specific version

2023-03-21 22:39 UTC, RothAndrew commented on examples/complete/main.tf
> +resource "aws_security_group" "remote_access" {
Is this security group and key pair something that should go in the EKS module? Feels kinda weird to be creating them separately

2023-03-21 22:39 UTC, RothAndrew commented on examples/complete/providers.tf
> +  required_version = ">= 1.3.0"
All the other `required_version` fields set `>= 1.0.0`. Is there anything that makes this different?

2023-03-22 04:13 UTC, zack-is-cool commented
/test all

2023-03-22 14:35 UTC, zack-is-cool commented on modules/eks/variables.tf
> +}
I added some (gross tf) logic to determine if `create_aws_auth_configmap` should be true or false in our eks module and removed the input variable - it is mutually exclusive with `eks_managed_node_groups` actually being created. This should fit all variations of how the upstream module works to prevent errors when deploying.

see: [`1aa2d67` (#96)](https://github.com/defenseunicorns/iac/pull/96/commits/1aa2d670014508ea371726075d223e32af2b7c39)

2023-03-22 14:41 UTC, zack-is-cool commented on examples/complete-self-managed-nodegroup/.terraform.lock.hcl
agree

2023-03-22 15:43 UTC, zack-is-cool commented on examples/complete-self-managed-nodegroup/outputs.tf
> +  value       = try(module.loki_s3_bucket.s3_bucket, null)
Pattern: use try() in outputs when it's iterating over a list

2023-03-22 16:08 UTC, zack-is-cool commented on examples/complete/variables.tf
> +variable "vpc_instance_tenancy" {
added validation and removed the input

2023-03-22 16:18 UTC, zack-is-cool commented on examples/complete/variables.tf
> +variable "cluster_version" {
added

2023-03-22 16:22 UTC, zack-is-cool commented on examples/complete/variables.tf
> +}
Resolved by implementing logic to determine if create_aws_auth_configmap should be created and removed the input

2023-03-22 16:28 UTC, zack-is-cool commented on examples/complete/main.tf
> +  version = "~> 2.0"
I removed this

2023-03-22 16:29 UTC, zack-is-cool commented on examples/complete/main.tf
> +resource "aws_security_group" "remote_access" {
I removed this

2023-03-22 16:36 UTC, zack-is-cool commented on examples/complete/main.tf
> +data "aws_ami" "eks_default" {
we don't need any of these, removed

2023-03-22 16:37 UTC, zack-is-cool commented on examples/complete-self-managed-nodegroup/variables.tf
> +variable "loki_s3_bucket_kms_key_alias" {
removed

2023-03-22 16:39 UTC, zack-is-cool commented on examples/complete-self-managed-nodegroup/terraform.tfvars.example
> +loki_s3_bucket_kms_key_alias = "my-loki-s3"
removed

2023-03-22 16:48 UTC, zack-is-cool commented on examples/complete-self-managed-nodegroup/terraform.tfvars.example
no. I'm not going to do it.

2023-03-22 17:18 UTC, zack-is-cool commented
/test all

2023-03-22 17:36 UTC, zack-is-cool commented
/test all
added some defaults to account for automatically getting current user info for "admin" stuff

2023-03-22 18:40 UTC, RothAndrew submitted a review, later dismissed

2023-03-22 19:44 UTC, zack-is-cool commented on .gitignore
> +
does this work?
```suggestion
```

2023-03-22 19:48 UTC, RothAndrew approved these changes

2023-03-23 20:32 UTC, ntwkninja approved these changes
Security features don't have parity but everything else looks good!

Will update existing EKS security group issue #17 and add others as needed to capture the delta

2023-03-23 21:25 UTC, RothAndrew approved these changes

2023-03-23 21:27 UTC, merged